version: '3.9'

services:
  db:
    image: postgres:15.3-alpine
    container_name: db
    env_file:
      - ../.env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
  
  backend:
    build: 
      context: ../ 
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - static_value:/lenta_app/staticfiles/
      - media_value:/lenta_app/media/
    depends_on:
      - db
    env_file:
      - ../.env_file

  ml:
    image: vdol22/lenta_model:lenta_model_11
    restart: always
    volumes:
      - ml_value:/lenta_app/ml/
  
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/docs/
      - static_value:/var/html/staticfiles/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - backend
  

volumes:
  db_data:
  static_value: 
  media_value: 
